- id: eslint
  name: eslint
  language: node
  entry: eslint --fix
  types_or: [ts, tsx]
  additional_dependencies:
    - "typescript@4.5.4"
    - "@typescript-eslint/parser@5.59.7"
    - "@typescript-eslint/eslint-plugin@5.59.7"
    - "eslint@8.41.0"
    - "eslint-plugin-prettier@4.2.1"
