- id: tsclint
  name: tsclint
  description: Lint using typescript's compiler
  language: node
  entry: eslint
  types_or: [ts, tsx]
  additional_dependencies:
    - "typescript@4.5.4"
    - "@typescript-eslint/parser@5.59.7"
    - "@typescripot-eslint/eslint-plugin@5.59.7"
    - "eslint@8.41.0"
